### ISSUE TITLE
Arduino IDE 1.6 support

### ISSUE THREAD

**Issue by emericg** [wasdpkj/Microduino-IDE#1]
Hi,
Arduino IDE 1.5 beta has been available for years, and the new Arduino IDE 1.6 (with "board manager" and "library manager" support)

When are you planning to support Arduino IDE 1.6? It is the new default, and mandatory for people like me also using 32b AVR or ARM boards like Arduino DUE.

**Comment by emericg** [comment]
Nevermind... https://github.com/emericg/MicroduinoBoards

**Comment by wasdpkj** [comment]
Sorry Emeric，I saw your mail too late；
These days I have also made a 1.63 version of the hardware support package
This version is still in beta（only support windows os now）：
http://pan.baidu.com/s/1jGpFUaa
https://github.com/wasdpkj/Microduino-IDE

Thank you for your support!

Kejia Pan

wasdpkj@hotmail.com 

From: Emeric
Date: 2015-04-30 02:26
To: wasdpkj/Microduino-IDE
Subject: Re: [Microduino-IDE] Arduino IDE 1.6 support (#1)
Nevermind... https://github.com/emericg/MicroduinoBoards

**Comment by emericg** [comment]
Hi !
Thank you for your answer. I really prefer having an Microduino "Hardware Support Package" separated from a complete IDE, because of the multiplatform support and the possibility to update the IDE and the HSP separatly, so I will keep updating this repository.

But can I ask what where the motivation for the Microduino IDE, and would that not be simplier to cleanly integrate and HSP into the new "board manager" of the new Arduino IDE ?

**Comment by wasdpkj** [comment]
We do provide Microduino hardware and library pacakge for Arduino IDE (board manager). Download from here 
https://github.com/wasdpkj/Microduino-IDE/tree/master/arduino-ide(Support)

A specific Microduino IDE also available, the purposes is to support some special Microduino-Core modules, such as Microduino-CoreRF module, we have to revise original Arduino IDE to support it. and CoreRF is cool and powerful, try it! 

wasdpkj@hotmail.com

From: Emeric
Date: 2015-05-05 20:45
To: wasdpkj/Microduino-IDE
CC: 老潘orz
Subject: Re: [Microduino-IDE] Arduino IDE 1.6 support (#1)
Hi !
Thank you for your answer. I really prefer having an Microduino "Hardware Support Package" separated from a complete IDE, because of the multiplatform support and the possibility to update the IDE and the HSP separatly, so I will keep updating this repository.
But can I ask what where the motivation for the Microduino IDE, and would that not be simplier to cleanly integrate and HSP into the new "board manager" of the new Arduino IDE ?
